### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by jjotta158** [jjotta158/rooms_manager#1]
- [x]  Read Node documentation
- [ ]  Read the TypeScript documentation
- [ ]  creating the TypeScript configuration if have one
- [ ]  create database
- [ ]  create the backend of application using TS, Node, and Sequelize
